title: Eoin Houstoun
logo: docs/assets/headshot.png
description: >
  Data Scientist | AI Scientist |  
  Machine Learning Engineer  
  
  Based in London  
  
  MSc Data Science & AI, Goldsmiths,University of London (2024–2025) — First-Class Honours  
  
  BSc Data Science & Analytics, UCC (2020–2024) — First-Class Honours  
  
  eoinhoustoun@hotmail.com  
  LinkedIn: linkedin.com/in/eoin-houstoun-b0322b231/

show_downloads: false
theme: jekyll-theme-minimal
