title: Eoin Houstoun
logo: docs/assets/headshot.png
description: >
  Data Scientist | AI Scientist | Machine Learning Engineer

show_downloads: false
theme: jekyll-theme-merlot

# Social links
github:
  is_project_page: false

# Optional: contact buttons or links (custom later)
